### ISSUE TITLE
command artic-tools get_scheme don't work

### ISSUE THREAD

**Issue by arturomarin** [will-rowe/artic-tools#11]
Hi developer,

I am try to use artic-tools for doing some task. When I use the command:

`artic-tools get_scheme nCoV-2019 --schemeVersion 3`

or --schemeVersion 2 or --schemeVersion 3, only downloaded the files **.primer.bed** and **.reference.fasta**. The files **.insert.bed** and **.tsv** is not downloaded.

Thanks,

**Comment by will-rowe** [comment]
Hi there @arturomarin,

Thanks for getting in touch. It is actually working as intended - the get_scheme command only collects a primer bed file and the reference sequence as that are the only requirements for the artic pipeline.

You can always download the scheme and then generate the insert.bed file like this:

```
artic-tools validate_scheme --outputInserts INSERTS.bed some.scheme.bed
```

Or just download direct from [the ARTIC schemes repo](https://github.com/artic-network/primer-schemes).
